# Generated by Django 5.2.6 on 2025-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do pokemon:')),
                ('img', models.URLField()),
                ('peso', models.FloatField()),
                ('tipo1', models.CharField(max_length=20)),
                ('tipo2', models.CharField(blank=True, max_length=20)),
                ('hp', models.IntegerField()),
                ('forca', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('forca_esp', models.IntegerField()),
                ('defesa_esp', models.IntegerField()),
                ('velocidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pokemon Favorito',
                'verbose_name_plural': 'Pokemons Favoritos',
            },
        ),
    ]
