# Generated by Django 5.2.6 on 2025-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.IntegerField(max_length=100, unique=True)),
                ('imagem', models.URLField(unique=True)),
            ],
        ),
    ]
